# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2003 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C07
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<


Borland:  \
	Apply.exe \
	AssocInserter.exe \
	BankTeller.exe \
	BasicSequenceOperations.exe \
	FEditTest.exe \
	FileEditor.$(OBJEXT) \
	IndexingVsAt.exe \
	Inserters.exe \
	Intset.exe \
	ListSpecialFunctions.exe \
	ListVsSet.exe \
	MultiSet1.exe \
	MultiSetWordCount.exe \
	NoisyMap.exe \
	PriorityQueue1.exe \
	PriorityQueue2.exe \
	PriorityQueue3.exe \
	PriorityQueue4.exe \
	PriorityQueue5.exe \
	PriorityQueue6.exe \
	PriorityQueue7.exe \
	PriorityQueue8.exe \
	Reversible.exe \
	Ring.exe \
	Stack1.exe \
	Stack2.exe \
	Stack3.exe \
	Stlshape.exe \
	Stlshape2.exe \
	StreambufIterator.exe \
	StreamIt.exe \
	StringDeque.exe \
	StringVector.exe \
	Thesaurus.exe \
	TokenIteratorTest.exe \
	UniqueList.exe \
	VectorCoreDump.exe \
	VectorOfBool.exe \
	WildLifeMonitor.exe \
	WordCount.exe \
	WordList.exe \
	WordList2.exe \
	WordSet.exe

Microsoft:  \
	Apply.exe \
	AssociativeBasics.exe \
	AssocInserter.exe \
	BankTeller.exe \
	BasicSequenceOperations.exe \
	BitSet.exe \
	DequeConversion.exe \
	DequeOverflow.exe \
	FEditTest.exe \
	FileEditor.$(OBJEXT) \
	IndexingVsAt.exe \
	Inserters.exe \
	Intset.exe \
	ListSpecialFunctions.exe \
	ListStability.exe \
	ListVsSet.exe \
	MultiSet1.exe \
	MultiSetWordCount.exe \
	NoisyMap.exe \
	PriorityQueue1.exe \
	PriorityQueue2.exe \
	PriorityQueue3.exe \
	PriorityQueue4.exe \
	PriorityQueue5.exe \
	PriorityQueue6.exe \
	PriorityQueue7.exe \
	PriorityQueue8.exe \
	RawStorageIterator.exe \
	Reversible.exe \
	Ring.exe \
	Stack1.exe \
	Stack2.exe \
	Stack3.exe \
	Stlshape.exe \
	Stlshape2.exe \
	StreambufIterator.exe \
	StreamIt.exe \
	StringDeque.exe \
	StringVector.exe \
	Swapping.exe \
	UniqueList.exe \
	Valarray1.exe \
	Valarray2.exe \
	VectorCoreDump.exe \
	VectorInsertAndErase.exe \
	VectorOfBool.exe \
	VectorOverflow.exe \
	WildLifeMonitor.exe \
	WordCount.exe \
	WordList.exe \
	WordList2.exe \
	WordSet.exe

g++:  \
	Apply.exe \
	AssociativeBasics.exe \
	AssocInserter.exe \
	BankTeller.exe \
	BasicSequenceOperations.exe \
	BitSet.exe \
	DequeConversion.exe \
	DequeOverflow.exe \
	FEditTest.exe \
	FileEditor.$(OBJEXT) \
	IndexingVsAt.exe \
	Inserters.exe \
	Intset.exe \
	ListSpecialFunctions.exe \
	ListStability.exe \
	ListVsSet.exe \
	MultiSet1.exe \
	MultiSetWordCount.exe \
	NoisyMap.exe \
	PriorityQueue1.exe \
	PriorityQueue2.exe \
	PriorityQueue3.exe \
	PriorityQueue4.exe \
	PriorityQueue5.exe \
	PriorityQueue6.exe \
	PriorityQueue7.exe \
	PriorityQueue8.exe \
	RawStorageIterator.exe \
	Reversible.exe \
	Ring.exe \
	Stack1.exe \
	Stack2.exe \
	Stack3.exe \
	Stlshape.exe \
	Stlshape2.exe \
	StreambufIterator.exe \
	StreamIt.exe \
	StringDeque.exe \
	StringVector.exe \
	Swapping.exe \
	TokenIteratorTest.exe \
	UniqueList.exe \
	Valarray1.exe \
	Valarray2.exe \
	VectorCoreDump.exe \
	VectorInsertAndErase.exe \
	VectorOfBool.exe \
	VectorOverflow.exe \
	WildLifeMonitor.exe \
	WordCount.exe \
	WordList.exe \
	WordList2.exe \
	WordSet.exe

edg:  \
	Apply.exe \
	AssociativeBasics.exe \
	AssocInserter.exe \
	BankTeller.exe \
	BasicSequenceOperations.exe \
	BitSet.exe \
	DequeConversion.exe \
	DequeOverflow.exe \
	FEditTest.exe \
	FileEditor.$(OBJEXT) \
	IndexingVsAt.exe \
	Inserters.exe \
	Intset.exe \
	ListSpecialFunctions.exe \
	ListStability.exe \
	ListVsSet.exe \
	MapVsHashMap.exe \
	MultiSet1.exe \
	MultiSetWordCount.exe \
	NoisyMap.exe \
	PriorityQueue1.exe \
	PriorityQueue2.exe \
	PriorityQueue3.exe \
	PriorityQueue4.exe \
	PriorityQueue5.exe \
	PriorityQueue6.exe \
	PriorityQueue7.exe \
	PriorityQueue8.exe \
	RawStorageIterator.exe \
	Reversible.exe \
	Ring.exe \
	Stack1.exe \
	Stack2.exe \
	Stack3.exe \
	Stlshape.exe \
	Stlshape2.exe \
	StreambufIterator.exe \
	StreamIt.exe \
	StringDeque.exe \
	StringVector.exe \
	Swapping.exe \
	Thesaurus.exe \
	TokenIteratorTest.exe \
	UniqueList.exe \
	Valarray1.exe \
	Valarray2.exe \
	VectorCoreDump.exe \
	VectorInsertAndErase.exe \
	VectorOfBool.exe \
	VectorOverflow.exe \
	WildLifeMonitor.exe \
	WordCount.exe \
	WordList.exe \
	WordList2.exe \
	WordSet.exe

Metrowerks:  \
	Apply.exe \
	AssociativeBasics.exe \
	AssocInserter.exe \
	BankTeller.exe \
	BasicSequenceOperations.exe \
	BitSet.exe \
	DequeConversion.exe \
	DequeOverflow.exe \
	FEditTest.exe \
	FileEditor.$(OBJEXT) \
	IndexingVsAt.exe \
	Inserters.exe \
	Intset.exe \
	ListSpecialFunctions.exe \
	ListStability.exe \
	ListVsSet.exe \
	MapVsHashMap.exe \
	MultiSet1.exe \
	MultiSetWordCount.exe \
	NoisyMap.exe \
	PriorityQueue1.exe \
	PriorityQueue2.exe \
	PriorityQueue3.exe \
	PriorityQueue4.exe \
	PriorityQueue5.exe \
	PriorityQueue6.exe \
	PriorityQueue7.exe \
	PriorityQueue8.exe \
	RawStorageIterator.exe \
	Reversible.exe \
	Ring.exe \
	Stack1.exe \
	Stack2.exe \
	Stack3.exe \
	Stlshape.exe \
	Stlshape2.exe \
	StreambufIterator.exe \
	StreamIt.exe \
	StringDeque.exe \
	StringVector.exe \
	Swapping.exe \
	Thesaurus.exe \
	TokenIteratorTest.exe \
	UniqueList.exe \
	Valarray1.exe \
	Valarray2.exe \
	VectorCoreDump.exe \
	VectorInsertAndErase.exe \
	VectorOfBool.exe \
	VectorOverflow.exe \
	WildLifeMonitor.exe \
	WordCount.exe \
	WordList.exe \
	WordList2.exe \
	WordSet.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


Apply.exe: Apply.cpp


AssociativeBasics.exe: AssociativeBasics.cpp


AssocInserter.exe: AssocInserter.cpp


BankTeller.exe: BankTeller.cpp


BasicSequenceOperations.exe: BasicSequenceOperations.cpp


BitSet.exe: BitSet.cpp


DequeConversion.exe: DequeConversion.cpp


DequeOverflow.exe: DequeOverflow.cpp


FEditTest.exe: FileEditor.$(OBJEXT) FEditTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)FEditTest.exe FEditTest.$(OBJEXT) FileEditor.$(OBJEXT)

FEditTest.$(OBJEXT): FEditTest.cpp

FileEditor.$(OBJEXT): FileEditor.cpp


IndexingVsAt.exe: IndexingVsAt.cpp


Inserters.exe: Inserters.cpp


Intset.exe: Intset.cpp


ListSpecialFunctions.exe: ListSpecialFunctions.cpp


ListStability.exe: ListStability.cpp


ListVsSet.exe: ListVsSet.cpp


MapVsHashMap.exe: MapVsHashMap.cpp


MultiSet1.exe: MultiSet1.cpp


MultiSetWordCount.exe: MultiSetWordCount.cpp


NoisyMap.exe: ../TestSuite/Test.$(OBJEXT) NoisyMap.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)NoisyMap.exe NoisyMap.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	NoisyMap.exe
endif

NoisyMap.$(OBJEXT): NoisyMap.cpp

PriorityQueue1.exe: PriorityQueue1.cpp


PriorityQueue2.exe: PriorityQueue2.cpp


PriorityQueue3.exe: PriorityQueue3.cpp


PriorityQueue4.exe: PriorityQueue4.cpp


PriorityQueue5.exe: PriorityQueue5.cpp


PriorityQueue6.exe: PriorityQueue6.cpp


PriorityQueue7.exe: PriorityQueue7.cpp


PriorityQueue8.exe: PriorityQueue8.cpp


RawStorageIterator.exe: RawStorageIterator.cpp


Reversible.exe: Reversible.cpp


Ring.exe: Ring.cpp


Stack1.exe: Stack1.cpp


Stack2.exe: Stack2.cpp


Stack3.exe: Stack3.cpp


Stlshape.exe: Stlshape.cpp


Stlshape2.exe: Stlshape2.cpp


StreambufIterator.exe: StreambufIterator.cpp


StreamIt.exe: StreamIt.cpp


StringDeque.exe: StringDeque.cpp


StringVector.exe: StringVector.cpp


Swapping.exe: Swapping.cpp


Thesaurus.exe: Thesaurus.cpp


TokenIteratorTest.exe: TokenIteratorTest.cpp


UniqueList.exe: UniqueList.cpp


Valarray1.exe: Valarray1.cpp


Valarray2.exe: Valarray2.cpp


VectorCoreDump.exe: VectorCoreDump.cpp


VectorInsertAndErase.exe: VectorInsertAndErase.cpp


VectorOfBool.exe: VectorOfBool.cpp


VectorOverflow.exe: VectorOverflow.cpp


WildLifeMonitor.exe: WildLifeMonitor.cpp


WordCount.exe: WordCount.cpp


WordList.exe: WordList.cpp


WordList2.exe: WordList2.cpp


WordSet.exe: WordSet.cpp


