# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2003 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C03
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<


Borland:  \
	AddStrings.exe \
	BadStringIndexing.exe \
	Compare.exe \
	Compare2.exe \
	CompStr.exe \
	ExtractCode.exe \
	Find.exe \
	HTMLStripper.exe \
	ICompare.exe \
	IWCompare.exe \
	Replace.exe \
	ReplaceAll.$(OBJEXT) \
	ReplaceAllTest.exe \
	ReplaceAndGrow.exe \
	Rparse.exe \
	Sieve.exe \
	SmallString.exe \
	SmallString2.exe \
	StringCharReplace.exe \
	StringIndexing.exe \
	StringIterators.exe \
	StringReplace.exe \
	StringStorage.exe \
	StrSize.exe \
	Tracetst.exe \
	TrimTest.exe \
	UhOh.exe

Microsoft:  \
	AddStrings.exe \
	BadStringIndexing.exe \
	Compare.exe \
	Compare2.exe \
	CompStr.exe \
	ExtractCode.exe \
	Find.exe \
	HTMLStripper.exe \
	ICompare.exe \
	IWCompare.exe \
	Replace.exe \
	ReplaceAll.$(OBJEXT) \
	ReplaceAndGrow.exe \
	Rparse.exe \
	Sieve.exe \
	SmallString.exe \
	SmallString2.exe \
	StringCharReplace.exe \
	StringIndexing.exe \
	StringIterators.exe \
	StringReplace.exe \
	StringStorage.exe \
	StrSize.exe \
	Tracetst.exe \
	TrimTest.exe \
	UhOh.exe

g++:  \
	AddStrings.exe \
	BadStringIndexing.exe \
	Compare.exe \
	Compare2.exe \
	CompStr.exe \
	ExtractCode.exe \
	Find.exe \
	HTMLStripper.exe \
	ICompare.exe \
	Replace.exe \
	ReplaceAll.$(OBJEXT) \
	ReplaceAllTest.exe \
	ReplaceAndGrow.exe \
	Rparse.exe \
	Sieve.exe \
	SmallString.exe \
	SmallString2.exe \
	StringCharReplace.exe \
	StringIndexing.exe \
	StringIterators.exe \
	StringReplace.exe \
	StringStorage.exe \
	StrSize.exe \
	Tracetst.exe \
	TrimTest.exe \
	UhOh.exe

edg:  \
	AddStrings.exe \
	BadStringIndexing.exe \
	Compare.exe \
	Compare2.exe \
	CompStr.exe \
	ExtractCode.exe \
	Find.exe \
	HTMLStripper.exe \
	ICompare.exe \
	IWCompare.exe \
	Replace.exe \
	ReplaceAll.$(OBJEXT) \
	ReplaceAllTest.exe \
	ReplaceAndGrow.exe \
	Rparse.exe \
	Sieve.exe \
	SmallString.exe \
	SmallString2.exe \
	StringCharReplace.exe \
	StringIndexing.exe \
	StringIterators.exe \
	StringReplace.exe \
	StringStorage.exe \
	StrSize.exe \
	Tracetst.exe \
	TrimTest.exe \
	UhOh.exe

Metrowerks:  \
	AddStrings.exe \
	BadStringIndexing.exe \
	Compare.exe \
	Compare2.exe \
	CompStr.exe \
	ExtractCode.exe \
	Find.exe \
	HTMLStripper.exe \
	ICompare.exe \
	IWCompare.exe \
	Replace.exe \
	ReplaceAll.$(OBJEXT) \
	ReplaceAllTest.exe \
	ReplaceAndGrow.exe \
	Rparse.exe \
	Sieve.exe \
	SmallString.exe \
	SmallString2.exe \
	StringCharReplace.exe \
	StringIndexing.exe \
	StringIterators.exe \
	StringReplace.exe \
	StringStorage.exe \
	StrSize.exe \
	Tracetst.exe \
	TrimTest.exe \
	UhOh.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


AddStrings.exe: AddStrings.cpp


BadStringIndexing.exe: BadStringIndexing.cpp


Compare.exe: Compare.cpp


Compare2.exe: Compare2.cpp


CompStr.exe: ../TestSuite/Test.$(OBJEXT) CompStr.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)CompStr.exe CompStr.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	CompStr.exe
endif

CompStr.$(OBJEXT): CompStr.cpp

ExtractCode.exe: ExtractCode.cpp


Find.exe: ../TestSuite/Test.$(OBJEXT) Find.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Find.exe Find.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Find.exe
endif

Find.$(OBJEXT): Find.cpp

HTMLStripper.exe: ReplaceAll.$(OBJEXT) HTMLStripper.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)HTMLStripper.exe HTMLStripper.$(OBJEXT) ReplaceAll.$(OBJEXT)

HTMLStripper.$(OBJEXT): HTMLStripper.cpp

ICompare.exe: ICompare.cpp


IWCompare.exe: IWCompare.cpp


Replace.exe: Replace.cpp


ReplaceAll.$(OBJEXT): ReplaceAll.cpp


ReplaceAllTest.exe: ReplaceAll.$(OBJEXT) ReplaceAllTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)ReplaceAllTest.exe ReplaceAllTest.$(OBJEXT) ReplaceAll.$(OBJEXT)

ReplaceAllTest.$(OBJEXT): ReplaceAllTest.cpp

ReplaceAndGrow.exe: ReplaceAndGrow.cpp


Rparse.exe: ../TestSuite/Test.$(OBJEXT) Rparse.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Rparse.exe Rparse.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Rparse.exe
endif

Rparse.$(OBJEXT): Rparse.cpp

Sieve.exe: ../TestSuite/Test.$(OBJEXT) Sieve.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Sieve.exe Sieve.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Sieve.exe
endif

Sieve.$(OBJEXT): Sieve.cpp

SmallString.exe: SmallString.cpp


SmallString2.exe: SmallString2.cpp


StringCharReplace.exe: StringCharReplace.cpp


StringIndexing.exe: StringIndexing.cpp


StringIterators.exe: StringIterators.cpp


StringReplace.exe: StringReplace.cpp


StringStorage.exe: ../TestSuite/Test.$(OBJEXT) StringStorage.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)StringStorage.exe StringStorage.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	StringStorage.exe
endif

StringStorage.$(OBJEXT): StringStorage.cpp

StrSize.exe: StrSize.cpp


Tracetst.exe: Tracetst.cpp


TrimTest.exe: ../TestSuite/Test.$(OBJEXT) TrimTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)TrimTest.exe TrimTest.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	TrimTest.exe
endif

TrimTest.$(OBJEXT): TrimTest.cpp

UhOh.exe: UhOh.cpp


