# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2003 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C05
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<


Borland:  \
	Accumulate.exe \
	ApplyGromit.exe \
	ArraySize.exe \
	Box1.exe \
	Box2.exe \
	Conditionals.exe \
	CountedClass.exe \
	CountedClass2.exe \
	CountedClass3.exe \
	DelayedInstantiation.exe \
	DotTemplate.exe \
	Factorial.exe \
	Fibonacci.exe \
	FriendScope.exe \
	FriendScope2.exe \
	FuncDef.exe \
	ImplicitCast.exe \
	Max.exe \
	MemberClass.exe \
	MinInstances.$(OBJEXT) \
	MinMain.exe \
	MinTest.exe \
	MinTest2.exe \
	MyVector.exe \
	MyVector2.exe \
	NobloatTest.exe \
	OurMin.$(OBJEXT) \
	PartialOrder.exe \
	PartialOrder2.exe \
	PoohCorner.exe \
	PoohCorner2.exe \
	Power.exe \
	PrintSeq.exe \
	Sorted.exe \
	StaticAssert.exe \
	StringConvTest.exe \
	StrTolower.$(OBJEXT) \
	TemplateFunctionAddress.exe \
	TempTemp.exe \
	TempTemp2.exe \
	Tolower.exe \
	ToLower2.exe \
	Unroll.exe \
	UseMin1.$(OBJEXT) \
	UseMin2.$(OBJEXT) \
	UsingTypename.exe

Microsoft:  \
	Accumulate.exe \
	ApplyGromit.exe \
	ArraySize.exe \
	Box1.exe \
	Box2.exe \
	Conditionals.exe \
	CountedClass.exe \
	CountedClass2.exe \
	CountedClass3.exe \
	DelayedInstantiation.exe \
	DotTemplate.exe \
	Factorial.exe \
	Fibonacci.exe \
	FriendScope.exe \
	FriendScope2.exe \
	FriendScope3.exe \
	FuncDef.exe \
	ImplicitCast.exe \
	Lookup2.exe \
	Max.exe \
	MemberClass.exe \
	MinInstances.$(OBJEXT) \
	MinMain.exe \
	MinTest.exe \
	MinTest2.exe \
	MyVector.exe \
	MyVector2.exe \
	NobloatTest.exe \
	OurMin.$(OBJEXT) \
	PartialOrder.exe \
	PartialOrder2.exe \
	PoohCorner.exe \
	PoohCorner2.exe \
	Power.exe \
	Sorted.exe \
	StaticAssert.exe \
	StringConvTest.exe \
	StrTolower.$(OBJEXT) \
	TemplateFunctionAddress.exe \
	TempTemp.exe \
	TempTemp2.exe \
	Tolower.exe \
	ToLower2.exe \
	TypenamedID.exe \
	Unroll.exe \
	UrandTest.exe \
	UseMin1.$(OBJEXT) \
	UseMin2.$(OBJEXT) \
	UsingTypename.exe

g++:  \
	Accumulate.exe \
	ApplyGromit.exe \
	ArraySize.exe \
	Box1.exe \
	Box2.exe \
	Conditionals.exe \
	CountedClass.exe \
	CountedClass2.exe \
	CountedClass3.exe \
	DelayedInstantiation.exe \
	DotTemplate.exe \
	Factorial.exe \
	Fibonacci.exe \
	FriendScope.exe \
	FriendScope2.exe \
	FriendScope3.exe \
	FuncDef.exe \
	ImplicitCast.exe \
	Max.exe \
	MemberClass.exe \
	MinInstances.$(OBJEXT) \
	MinMain.exe \
	MinTest.exe \
	MinTest2.exe \
	MyVector.exe \
	MyVector2.exe \
	NobloatTest.exe \
	OurMin.$(OBJEXT) \
	PartialOrder.exe \
	PartialOrder2.exe \
	PoohCorner.exe \
	PoohCorner2.exe \
	Power.exe \
	PrintSeq.exe \
	Sorted.exe \
	StringConvTest.exe \
	StrTolower.$(OBJEXT) \
	TemplateFunctionAddress.exe \
	TempTemp.exe \
	TempTemp2.exe \
	TempTemp3.exe \
	TempTemp4.exe \
	Tolower.exe \
	ToLower2.exe \
	TypenamedID.exe \
	Unroll.exe \
	UrandTest.exe \
	UseMin1.$(OBJEXT) \
	UseMin2.$(OBJEXT) \
	UsingTypename.exe

edg:  \
	Accumulate.exe \
	ApplyGromit.exe \
	ArraySize.exe \
	Box1.exe \
	Box2.exe \
	Conditionals.exe \
	CountedClass.exe \
	CountedClass2.exe \
	CountedClass3.exe \
	DelayedInstantiation.exe \
	DotTemplate.exe \
	Factorial.exe \
	Fibonacci.exe \
	FriendScope.exe \
	FriendScope2.exe \
	FriendScope3.exe \
	FuncDef.exe \
	ImplicitCast.exe \
	Lookup2.exe \
	Max.exe \
	MemberClass.exe \
	MinInstances.$(OBJEXT) \
	MinMain.exe \
	MinTest.exe \
	MinTest2.exe \
	MyVector.exe \
	MyVector2.exe \
	NobloatTest.exe \
	OurMin.$(OBJEXT) \
	PartialOrder.exe \
	PartialOrder2.exe \
	PoohCorner.exe \
	PoohCorner2.exe \
	Power.exe \
	PrintSeq.exe \
	Sorted.exe \
	StaticAssert.exe \
	StringConvTest.exe \
	StrTolower.$(OBJEXT) \
	TemplateFunctionAddress.exe \
	TempTemp.exe \
	TempTemp2.exe \
	TempTemp3.exe \
	TempTemp4.exe \
	Tolower.exe \
	ToLower2.exe \
	TypenamedID.exe \
	Unroll.exe \
	UrandTest.exe \
	UseMin1.$(OBJEXT) \
	UseMin2.$(OBJEXT) \
	UsingTypename.exe

Metrowerks:  \
	Accumulate.exe \
	ApplyGromit.exe \
	ArraySize.exe \
	Box1.exe \
	Box2.exe \
	Conditionals.exe \
	CountedClass.exe \
	CountedClass2.exe \
	CountedClass3.exe \
	DelayedInstantiation.exe \
	DotTemplate.exe \
	Factorial.exe \
	Fibonacci.exe \
	FriendScope.exe \
	FriendScope2.exe \
	FriendScope3.exe \
	FuncDef.exe \
	ImplicitCast.exe \
	Lookup2.exe \
	Max.exe \
	MemberClass.exe \
	MinInstances.$(OBJEXT) \
	MinMain.exe \
	MinTest.exe \
	MinTest2.exe \
	MyVector.exe \
	MyVector2.exe \
	NobloatTest.exe \
	OurMin.$(OBJEXT) \
	PartialOrder.exe \
	PartialOrder2.exe \
	PoohCorner.exe \
	PoohCorner2.exe \
	Power.exe \
	PrintSeq.exe \
	Sorted.exe \
	StaticAssert.exe \
	StringConvTest.exe \
	StrTolower.$(OBJEXT) \
	TemplateFunctionAddress.exe \
	TempTemp.exe \
	TempTemp2.exe \
	TempTemp3.exe \
	TempTemp4.exe \
	Tolower.exe \
	ToLower2.exe \
	TypenamedID.exe \
	Unroll.exe \
	UrandTest.exe \
	UseMin1.$(OBJEXT) \
	UseMin2.$(OBJEXT) \
	UsingTypename.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


Accumulate.exe: Accumulate.cpp


ApplyGromit.exe: ApplyGromit.cpp


ArraySize.exe: ArraySize.cpp


Box1.exe: Box1.cpp


Box2.exe: Box2.cpp


Conditionals.exe: Conditionals.cpp


CountedClass.exe: CountedClass.cpp


CountedClass2.exe: CountedClass2.cpp


CountedClass3.exe: CountedClass3.cpp


DelayedInstantiation.exe: DelayedInstantiation.cpp


DotTemplate.exe: DotTemplate.cpp


Factorial.exe: Factorial.cpp


Fibonacci.exe: Fibonacci.cpp


FriendScope.exe: FriendScope.cpp


FriendScope2.exe: FriendScope2.cpp


FriendScope3.exe: FriendScope3.cpp


FuncDef.exe: FuncDef.cpp


ImplicitCast.exe: ImplicitCast.cpp


Lookup2.exe: Lookup2.cpp


Max.exe: Max.cpp


MemberClass.exe: MemberClass.cpp


MinInstances.$(OBJEXT): MinInstances.cpp


MinMain.exe: UseMin1.$(OBJEXT) UseMin2.$(OBJEXT) MinInstances.$(OBJEXT) MinMain.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)MinMain.exe MinMain.$(OBJEXT) UseMin1.$(OBJEXT) UseMin2.$(OBJEXT) MinInstances.$(OBJEXT)

MinMain.$(OBJEXT): MinMain.cpp

MinTest.exe: MinTest.cpp


MinTest2.exe: MinTest2.cpp


MyVector.exe: MyVector.cpp


MyVector2.exe: MyVector2.cpp


NobloatTest.exe: NobloatTest.cpp


OurMin.$(OBJEXT): OurMin.cpp


PartialOrder.exe: PartialOrder.cpp


PartialOrder2.exe: PartialOrder2.cpp


PoohCorner.exe: PoohCorner.cpp


PoohCorner2.exe: PoohCorner2.cpp


Power.exe: Power.cpp


PrintSeq.exe: PrintSeq.cpp


Sorted.exe: Sorted.cpp


StaticAssert.exe: StaticAssert.cpp


StringConvTest.exe: StringConvTest.cpp


StrTolower.$(OBJEXT): StrTolower.cpp


TemplateFunctionAddress.exe: TemplateFunctionAddress.cpp


TempTemp.exe: TempTemp.cpp


TempTemp2.exe: TempTemp2.cpp


TempTemp3.exe: TempTemp3.cpp


TempTemp4.exe: TempTemp4.cpp


Tolower.exe: StrTolower.$(OBJEXT) Tolower.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Tolower.exe Tolower.$(OBJEXT) StrTolower.$(OBJEXT)

Tolower.$(OBJEXT): Tolower.cpp

ToLower2.exe: ToLower2.cpp


TypenamedID.exe: TypenamedID.cpp


Unroll.exe: Unroll.cpp


UrandTest.exe: UrandTest.cpp


UseMin1.$(OBJEXT): UseMin1.cpp


UseMin2.$(OBJEXT): UseMin2.cpp


UsingTypename.exe: UsingTypename.cpp


