# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2003 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C06
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<


Borland:  \
	BinderValue.exe \
	CalcInventory.exe \
	Comparison.exe \
	ComposeFinal.exe \
	ComposeTry.exe \
	CopyInts.exe \
	CopyInts2.exe \
	CopyInts3.exe \
	CopyInts4.exe \
	CopyIntsFromFile.exe \
	CopyIntsToFile.exe \
	CopyStrings.exe \
	CopyStrings2.exe \
	CopyVector.exe \
	Counting.exe \
	CountNotEqual.exe \
	FBinder.exe \
	FillGenerateTest.exe \
	FindBlanks.exe \
	ForEach.exe \
	GreaterThanN.exe \
	InsertVector.exe \
	Manipulations.exe \
	MemFun1.exe \
	MemFun2.exe \
	MemFun3.exe \
	MergeTest.exe \
	NumericTest.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	Removing.exe \
	ReplaceStrings.exe \
	SearchReplace.exe \
	SetOperations.exe \
	SortedSearchTest.exe \
	SpecialList.exe \
	Transform.exe \
	TransformNames.exe

Microsoft:  \
	BinderValue.exe \
	CalcInventory.exe \
	Comparison.exe \
	ComposeFinal.exe \
	ComposeTry.exe \
	CopyInts.exe \
	CopyInts2.exe \
	CopyInts3.exe \
	CopyInts4.exe \
	CopyIntsFromFile.exe \
	CopyIntsToFile.exe \
	CopyStrings.exe \
	CopyStrings2.exe \
	CopyVector.exe \
	Counting.exe \
	CountNotEqual.exe \
	FBinder.exe \
	FillGenerateTest.exe \
	FindBlanks.exe \
	ForEach.exe \
	FunctionObjects.exe \
	GreaterThanN.exe \
	InsertVector.exe \
	Manipulations.exe \
	MemFun1.exe \
	MemFun2.exe \
	MemFun3.exe \
	MergeTest.exe \
	NumericTest.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	Removing.exe \
	ReplaceStrings.exe \
	SearchReplace.exe \
	SetOperations.exe \
	SortedSearchTest.exe \
	SpecialList.exe \
	Transform.exe \
	TransformNames.exe

g++:  \
	BinderValue.exe \
	CalcInventory.exe \
	Comparison.exe \
	ComposeFinal.exe \
	ComposeTry.exe \
	CopyInts.exe \
	CopyInts2.exe \
	CopyInts3.exe \
	CopyInts4.exe \
	CopyIntsFromFile.exe \
	CopyIntsToFile.exe \
	CopyStrings.exe \
	CopyStrings2.exe \
	CopyVector.exe \
	Counting.exe \
	CountNotEqual.exe \
	FBinder.exe \
	FillGenerateTest.exe \
	FindBlanks.exe \
	ForEach.exe \
	FunctionObjects.exe \
	GreaterThanN.exe \
	InsertVector.exe \
	Manipulations.exe \
	MemFun1.exe \
	MemFun2.exe \
	MemFun3.exe \
	MergeTest.exe \
	NumericTest.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	Removing.exe \
	ReplaceStrings.exe \
	SearchReplace.exe \
	SetOperations.exe \
	SortedSearchTest.exe \
	SpecialList.exe \
	Transform.exe \
	TransformNames.exe

edg:  \
	BinderValue.exe \
	CalcInventory.exe \
	Comparison.exe \
	ComposeFinal.exe \
	ComposeTry.exe \
	CopyInts.exe \
	CopyInts2.exe \
	CopyInts3.exe \
	CopyInts4.exe \
	CopyIntsFromFile.exe \
	CopyIntsToFile.exe \
	CopyStrings.exe \
	CopyStrings2.exe \
	CopyVector.exe \
	Counting.exe \
	CountNotEqual.exe \
	FBinder.exe \
	FillGenerateTest.exe \
	FindBlanks.exe \
	ForEach.exe \
	FunctionObjects.exe \
	GreaterThanN.exe \
	InsertVector.exe \
	Manipulations.exe \
	MemFun1.exe \
	MemFun2.exe \
	MemFun3.exe \
	MergeTest.exe \
	NumericTest.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	Removing.exe \
	ReplaceStrings.exe \
	SearchReplace.exe \
	SetOperations.exe \
	SortedSearchTest.exe \
	SpecialList.exe \
	Transform.exe \
	TransformNames.exe

Metrowerks:  \
	BinderValue.exe \
	CalcInventory.exe \
	Comparison.exe \
	ComposeFinal.exe \
	ComposeTry.exe \
	CopyInts.exe \
	CopyInts2.exe \
	CopyInts3.exe \
	CopyInts4.exe \
	CopyIntsFromFile.exe \
	CopyIntsToFile.exe \
	CopyStrings.exe \
	CopyStrings2.exe \
	CopyVector.exe \
	Counting.exe \
	CountNotEqual.exe \
	FBinder.exe \
	FillGenerateTest.exe \
	FindBlanks.exe \
	ForEach.exe \
	FunctionObjects.exe \
	GreaterThanN.exe \
	InsertVector.exe \
	Manipulations.exe \
	MemFun1.exe \
	MemFun2.exe \
	MemFun3.exe \
	MergeTest.exe \
	NumericTest.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	Removing.exe \
	ReplaceStrings.exe \
	SearchReplace.exe \
	SetOperations.exe \
	SortedSearchTest.exe \
	SpecialList.exe \
	Transform.exe \
	TransformNames.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


BinderValue.exe: BinderValue.cpp


CalcInventory.exe: CalcInventory.cpp


Comparison.exe: Comparison.cpp


ComposeFinal.exe: ComposeFinal.cpp


ComposeTry.exe: ComposeTry.cpp


CopyInts.exe: CopyInts.cpp


CopyInts2.exe: CopyInts2.cpp


CopyInts3.exe: CopyInts3.cpp


CopyInts4.exe: CopyInts4.cpp


CopyIntsFromFile.exe: CopyIntsFromFile.cpp


CopyIntsToFile.exe: CopyIntsToFile.cpp


CopyStrings.exe: CopyStrings.cpp


CopyStrings2.exe: CopyStrings2.cpp


CopyVector.exe: CopyVector.cpp


Counting.exe: Counting.cpp


CountNotEqual.exe: CountNotEqual.cpp


FBinder.exe: FBinder.cpp


FillGenerateTest.exe: FillGenerateTest.cpp


FindBlanks.exe: FindBlanks.cpp


ForEach.exe: ForEach.cpp


FunctionObjects.exe: FunctionObjects.cpp


GreaterThanN.exe: GreaterThanN.cpp


InsertVector.exe: InsertVector.cpp


Manipulations.exe: Manipulations.cpp


MemFun1.exe: MemFun1.cpp


MemFun2.exe: MemFun2.cpp


MemFun3.exe: MemFun3.cpp


MergeTest.exe: MergeTest.cpp


NumericTest.exe: ../TestSuite/Test.$(OBJEXT) NumericTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)NumericTest.exe NumericTest.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	NumericTest.exe
endif

NumericTest.$(OBJEXT): NumericTest.cpp

PtrFun1.exe: PtrFun1.cpp


PtrFun2.exe: PtrFun2.cpp


Removing.exe: Removing.cpp


ReplaceStrings.exe: ReplaceStrings.cpp


SearchReplace.exe: SearchReplace.cpp


SetOperations.exe: SetOperations.cpp


SortedSearchTest.exe: SortedSearchTest.cpp


SpecialList.exe: SpecialList.cpp


Transform.exe: Transform.cpp


TransformNames.exe: TransformNames.cpp


