# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2003 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C04
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<


Borland:  \
	Cppcheck.exe \
	Datagen.exe \
	DataLogger.$(OBJEXT) \
	Datascan.exe \
	DateIOTest.exe \
	Effector.exe \
	Exercise16.exe \
	FileClass.$(OBJEXT) \
	FileClassTest.exe \
	Format.exe \
	HTMLStripper2.exe \
	InputWidth.exe \
	Iofile.exe \
	Iosexamp.exe \
	Istring.exe \
	Manips.exe \
	nl.exe \
	Ostring.exe \
	Sbufget.exe \
	Seeking.exe \
	Showerr.exe \
	Strfile.exe \
	Stype.exe \
	Unitbuf.exe

Microsoft:  \
	Cppcheck.exe \
	Datagen.exe \
	DataLogger.$(OBJEXT) \
	Datascan.exe \
	DateIOTest.exe \
	Effector.exe \
	Exercise16.exe \
	Facets.exe \
	FileClass.$(OBJEXT) \
	FileClassTest.exe \
	Format.exe \
	HTMLStripper2.exe \
	InputWidth.exe \
	Iofile.exe \
	Iosexamp.exe \
	Istring.exe \
	Locale.exe \
	Manips.exe \
	nl.exe \
	Ostring.exe \
	Sbufget.exe \
	Seeking.exe \
	Showerr.exe \
	Strfile.exe \
	StringSeeking.exe \
	Stype.exe \
	Unitbuf.exe

g++:  \
	Cppcheck.exe \
	Datagen.exe \
	DataLogger.$(OBJEXT) \
	Datascan.exe \
	DateIOTest.exe \
	Effector.exe \
	Exercise16.exe \
	FileClass.$(OBJEXT) \
	FileClassTest.exe \
	Format.exe \
	HTMLStripper2.exe \
	InputWidth.exe \
	Iofile.exe \
	Iosexamp.exe \
	Istring.exe \
	Manips.exe \
	nl.exe \
	Ostring.exe \
	Sbufget.exe \
	Seeking.exe \
	Showerr.exe \
	Strfile.exe \
	StringSeeking.exe \
	Stype.exe \
	Unitbuf.exe

edg:  \
	Cppcheck.exe \
	Datagen.exe \
	DataLogger.$(OBJEXT) \
	Datascan.exe \
	DateIOTest.exe \
	Effector.exe \
	Exercise16.exe \
	Facets.exe \
	FileClass.$(OBJEXT) \
	FileClassTest.exe \
	Format.exe \
	HTMLStripper2.exe \
	InputWidth.exe \
	Iofile.exe \
	Iosexamp.exe \
	Istring.exe \
	Manips.exe \
	nl.exe \
	Ostring.exe \
	Sbufget.exe \
	Seeking.exe \
	Showerr.exe \
	Strfile.exe \
	StringSeeking.exe \
	Stype.exe \
	Unitbuf.exe

Metrowerks:  \
	Cppcheck.exe \
	Datagen.exe \
	DataLogger.$(OBJEXT) \
	Datascan.exe \
	DateIOTest.exe \
	Effector.exe \
	Exercise16.exe \
	Facets.exe \
	FileClass.$(OBJEXT) \
	FileClassTest.exe \
	Format.exe \
	HTMLStripper2.exe \
	InputWidth.exe \
	Iofile.exe \
	Iosexamp.exe \
	Istring.exe \
	Locale.exe \
	Manips.exe \
	nl.exe \
	Ostring.exe \
	Sbufget.exe \
	Seeking.exe \
	Showerr.exe \
	Strfile.exe \
	StringSeeking.exe \
	Stype.exe \
	Unitbuf.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


Cppcheck.exe: Cppcheck.cpp


Datagen.exe: DataLogger.$(OBJEXT) Datagen.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Datagen.exe Datagen.$(OBJEXT) DataLogger.$(OBJEXT)

Datagen.$(OBJEXT): Datagen.cpp

DataLogger.$(OBJEXT): DataLogger.cpp


Datascan.exe: DataLogger.$(OBJEXT) Datascan.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Datascan.exe Datascan.$(OBJEXT) DataLogger.$(OBJEXT)

Datascan.$(OBJEXT): Datascan.cpp

DateIOTest.exe: ../C02/Date.$(OBJEXT) DateIOTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)DateIOTest.exe DateIOTest.$(OBJEXT) ../C02/Date.$(OBJEXT)

DateIOTest.$(OBJEXT): DateIOTest.cpp

Effector.exe: Effector.cpp


Exercise16.exe: Exercise16.cpp


Facets.exe: Facets.cpp


FileClass.$(OBJEXT): FileClass.cpp


FileClassTest.exe: FileClass.$(OBJEXT) FileClassTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)FileClassTest.exe FileClassTest.$(OBJEXT) FileClass.$(OBJEXT)

FileClassTest.$(OBJEXT): FileClassTest.cpp

Format.exe: Format.cpp


HTMLStripper2.exe: ../C03/ReplaceAll.$(OBJEXT) HTMLStripper2.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)HTMLStripper2.exe HTMLStripper2.$(OBJEXT) ../C03/ReplaceAll.$(OBJEXT)

HTMLStripper2.$(OBJEXT): HTMLStripper2.cpp

InputWidth.exe: InputWidth.cpp


Iofile.exe: Iofile.cpp


Iosexamp.exe: Iosexamp.cpp


Istring.exe: Istring.cpp


Locale.exe: Locale.cpp


Manips.exe: Manips.cpp


nl.exe: nl.cpp


Ostring.exe: Ostring.cpp


Sbufget.exe: Sbufget.cpp


Seeking.exe: Seeking.cpp


Showerr.exe: Showerr.cpp


Strfile.exe: Strfile.cpp


StringSeeking.exe: StringSeeking.cpp


Stype.exe: Stype.cpp


Unitbuf.exe: Unitbuf.cpp


