# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2003 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C01
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<


Borland:  \
	Autoexcp.exe \
	Auto_ptr.exe \
	Basexcpt.exe \
	Cleanup.exe \
	MyError.exe \
	Nonlocal.exe \
	Nonlocal2.exe \
	Rawp.exe \
	SafeAssign.exe \
	StdExcept.exe \
	Terminator.exe \
	Unexpected.exe \
	Wrapped.exe

Microsoft:  \
	Autoexcp.exe \
	Auto_ptr.exe \
	BadException.exe \
	Basexcpt.exe \
	Cleanup.exe \
	FunctionTryBlock.exe \
	InitExcept.exe \
	MyError.exe \
	Nonlocal.exe \
	Nonlocal2.exe \
	Rawp.exe \
	SafeAssign.exe \
	StdExcept.exe \
	Terminator.exe \
	Wrapped.exe

g++:  \
	Autoexcp.exe \
	Auto_ptr.exe \
	BadException.exe \
	Basexcpt.exe \
	Cleanup.exe \
	FunctionTryBlock.exe \
	InitExcept.exe \
	MyError.exe \
	Nonlocal.exe \
	Nonlocal2.exe \
	Rawp.exe \
	SafeAssign.exe \
	StdExcept.exe \
	Terminator.exe \
	Unexpected.exe \
	Wrapped.exe

edg:  \
	Autoexcp.exe \
	Auto_ptr.exe \
	BadException.exe \
	Basexcpt.exe \
	Cleanup.exe \
	FunctionTryBlock.exe \
	InitExcept.exe \
	MyError.exe \
	Nonlocal.exe \
	Nonlocal2.exe \
	Rawp.exe \
	SafeAssign.exe \
	StdExcept.exe \
	Terminator.exe \
	Unexpected.exe \
	Wrapped.exe

Metrowerks:  \
	Autoexcp.exe \
	Auto_ptr.exe \
	BadException.exe \
	Basexcpt.exe \
	Cleanup.exe \
	FunctionTryBlock.exe \
	InitExcept.exe \
	MyError.exe \
	Nonlocal.exe \
	Nonlocal2.exe \
	Rawp.exe \
	SafeAssign.exe \
	StdExcept.exe \
	Terminator.exe \
	Unexpected.exe \
	Wrapped.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


Autoexcp.exe: Autoexcp.cpp


Auto_ptr.exe: Auto_ptr.cpp


BadException.exe: BadException.cpp


Basexcpt.exe: Basexcpt.cpp


Cleanup.exe: Cleanup.cpp


FunctionTryBlock.exe: FunctionTryBlock.cpp


InitExcept.exe: InitExcept.cpp


MyError.exe: MyError.cpp


Nonlocal.exe: Nonlocal.cpp


Nonlocal2.exe: Nonlocal2.cpp


Rawp.exe: Rawp.cpp


SafeAssign.exe: SafeAssign.cpp


StdExcept.exe: StdExcept.cpp


Terminator.exe: Terminator.cpp


Unexpected.exe: Unexpected.cpp


Wrapped.exe: Wrapped.cpp


